### ISSUE TITLE
Some missing files

### ISSUE THREAD

**Issue by arrufat** [reunanen/anno#25]
Hi, I would like to try this repository so I ran the following commands:

``` bash
git clone https://github.com/reunanen/anno
cd anno
git submodule init
git submodule update
qmake
```
And the output is:
```
WARNING: Failure to find: QResultImageView/qt-image-flood-fill/qfloodfill.cpp
WARNING: Failure to find: QResultImageView/qt-image-flood-fill/qfloodfill.h
```
So it seems that those two files are missing, or maybe I'm doing something wrong (not used to building Qt apps)

**Comment by reunanen** [comment]
Hi @arrufat, please try to run the following command in the repo root:

`git submodule update --init --recursive`

**Comment by arrufat** [comment]
Thanks for the quick reply, I did that, opened the `anno.pro` with Qt Creator, but I get a lot of erros about:
```
Makefile:583: warning: overriding recipe for target 'mainwindow.o'
Makefile:576: warning: ignoring old recipe for target 'mainwindow.o'
g++ -Wl,-rpath-link,/usr/lib -o anno main.o mainwindow.o mainwindow.o QResultImageView.o qfloodfill.o move-file-to-trash.o qrc_anno.o moc_mainwindow.o moc_QResultImageView.o   -lQt5UiTools -lQt5Widgets -lQt5Gui -lQt5Core /usr/lib/libGL.so -lpthread   
/usr/bin/ld: mainwindow.o: in function `QListSpecialMethods<QString>::~QListSpecialMethods()':
/home/adria/Projects/build-anno-Qt_5_12_3_in_PATH_System-Debug/../anno/mainwindow.cpp:43: multiple definition of `MainWindow::MainWindow(QWidget*)'; mainwindow.o:/home/adria/Projects/build-anno-Qt_5_12_3_in_PATH_System-Debug/../anno/mainwindow.cpp:43: first defined here
```

**Comment by reunanen** [comment]
Can you please try again now, with [this commit](https://github.com/reunanen/anno/commit/aadf91ed48bd3ea50d2c6b51fe9fa7b9c8ffe434) included (the commit is already in master, so a simple pull should do it).

No idea why that duplicate line has caused no problems on my machine. :-/

**Comment by arrufat** [comment]
Oh, it's working now, kiitos! :D
